#!/bin/bash

# Utilizar a contagem de nano segundos
# UNIX time + número aleatório da builtin
# RANDOM + soma hash para geração de
# uma senha aleatória, bem como especificar
# o tamanho da senha para 32 caractéres
PASSWORD_TMP=$(date +%s%N${RANDOM} | sha256sum | head -c32)
# Adicionar alguns caracteres especiais
SYMBOLS=$(echo '!@#$%^&*()_-+=' | fold -w1 | shuf | head -c3)
# Formatar a senha final
# Concatenar as duas variáveis
PASSWORD_TMP_2="${PASSWORD_TMP}${SYMBOLS}"
# Embaralhar os caracteres da string final
FINAL_PASSWORD=$(echo "$PASSWORD_TMP_2" | fold -w1 | shuf | tr -d '\n')
echo "${FINAL_PASSWORD}"

